# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/liu/Code/ICEHelper/ui/root.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ICEHelper(object):
    def setupUi(self, ICEHelper):
        ICEHelper.setObjectName("ICEHelper")
        ICEHelper.resize(1088, 724)
        ICEHelper.setMinimumSize(QtCore.QSize(1080, 700))
        self.centralwidget = QtWidgets.QWidget(ICEHelper)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.gridLayout.addWidget(self.stackedWidget, 0, 0, 1, 1)
        ICEHelper.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(ICEHelper)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1088, 37))
        self.menuBar.setObjectName("menuBar")
        self.menuTools = QtWidgets.QMenu(self.menuBar)
        self.menuTools.setObjectName("menuTools")
        self.menuOption = QtWidgets.QMenu(self.menuBar)
        self.menuOption.setObjectName("menuOption")
        ICEHelper.setMenuBar(self.menuBar)
        self.actionopen = QtWidgets.QAction(ICEHelper)
        self.actionopen.setObjectName("actionopen")
        self.actionBMI = QtWidgets.QAction(ICEHelper)
        self.actionBMI.setObjectName("actionBMI")
        self.actionExcelColFilter = QtWidgets.QAction(ICEHelper)
        self.actionExcelColFilter.setObjectName("actionExcelColFilter")
        self.actionExcel = QtWidgets.QAction(ICEHelper)
        self.actionExcel.setObjectName("actionExcel")
        self.menuTools.addAction(self.actionBMI)
        self.menuOption.addAction(self.actionExcelColFilter)
        self.menuBar.addAction(self.menuTools.menuAction())
        self.menuBar.addAction(self.menuOption.menuAction())

        self.retranslateUi(ICEHelper)
        QtCore.QMetaObject.connectSlotsByName(ICEHelper)

    def retranslateUi(self, ICEHelper):
        _translate = QtCore.QCoreApplication.translate
        ICEHelper.setWindowTitle(_translate("ICEHelper", "ICE Helper"))
        self.menuTools.setTitle(_translate("ICEHelper", "Calc"))
        self.menuOption.setTitle(_translate("ICEHelper", "Process"))
        self.actionopen.setText(_translate("ICEHelper", "open"))
        self.actionBMI.setText(_translate("ICEHelper", "BMI"))
        self.actionExcelColFilter.setText(_translate("ICEHelper", "ExcelColFilter"))
        self.actionExcel.setText(_translate("ICEHelper", "Excel"))
